In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
pwd

'C:\\Users\\Admin\\Desktop\\PW\\PredictivePacers\\ipynb'

In [3]:
df = pd.read_csv(r"C:\\Users\\Admin\\Desktop\\PW\\PredictivePacers\\Processed Data\\hw_ind.csv")
df.drop(['Span'],axis = 1, inplace =True)
df.replace('-', 0, inplace=True)

df = df.dropna()

df

,Player,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,Mohammed Shami,17,17,146.2,5,867,30,May-51,28.9,5.92,29.2,1,1
1,Kuldeep Yadav,17,17,154,2,922,24,Mar-54,38.41,5.98,38.5,0,0
2,JJ Bumrah,15,15,144.3,6,779,21,Mar-61,37.09,5.39,41.2,0,0
3,RA Jadeja,20,19,181.2,4,930,19,28-Mar,48.94,5.12,57.2,0,0
4,B Kumar,6,6,57,1,304,15,Apr-45,20.26,5.33,22.8,1,0
5,YS Chahal,5,5,49,0,344,10,Jun-42,34.4,7.02,29.4,0,1
6,Mohammed Siraj,6,6,41.1,3,273,7,29-Mar,39,6.63,35.2,0,0
7,HH Pandya,8,6,31,0,211,6,Mar-44,35.16,6.8,31,0,0
8,R Ashwin,3,3,27,1,122,5,Mar-41,24.4,4.51,32.4,0,0
9,NA Saini,4,4,37,0,280,4,Feb-62,70,7.56,55.5,0,0
10,M Prasidh Krishna,2,2,11,0,101,3,Feb-56,33.66,9.18,22,0,0
11,SN Thakur,5,5,31,1,219,3,Mar-51,73,7.06,62,0,0
12,KM Jadhav,7,7,30,0,197,2,31-Jan,98.5,6.56,90,0,0
13,T Natarajan,1,1,10,1,70,2,Feb-70,35,7,30,0,0
14,AR Patel,2,2,11,0,82,2,Feb-57,41,7.45,33,0,0
15,V Shankar,6,5,23.3,0,133,2,15-Feb,66.5,5.65,70.5,0,0
16,MA Agarwal,2,1,1,0,10,0,0,0,10,0,0,0
17,KK Ahmed,1,1,8,0,55,0,0,0,6.87,0,0,0
18,AT Rayudu,5,1,2,0,13,0,0,0,6.5,0,0,0
19,Washington Sundar,1,1,10,0,48,0,0,0,4.8,0,0,0
20,S Dhawan,15,0,0,0,0,0,0,0,0,0,0,0
21,MS Dhoni,7,0,0,0,0,0,0,0,0,0,0,0
22,RD Gaikwad,2,0,0,0,0,0,0,0,0,0,0,0
23,Ishan Kishan,4,0,0,0,0,0,0,0,0,0,0,0
24,SS Iyer,10,0,0,0,0,0,0,0,0,0,0,0
25,KD Karthik,3,0,0,0,0,0,0,0,0,0,0,0
26,V Kohli,20,0,0,0,0,0,0,0,0,0,0,0
27,MK Pandey,2,0,0,0,0,0,0,0,0,0,0,0
28,RR Pant,3,0,0,0,0,0,0,0,0,0,0,0
29,KL Rahul,15,0,0,0,0,0,0,0,0,0,0,0
30,RG Sharma,16,0,0,0,0,0,0,0,0,0,0,0
31,Shubman Gill,6,0,0,0,0,0,0,0,0,0,0,0
32,SA Yadav,6,0,0,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np


features = ['Ave', 'Econ']
X = df[features]
y = df['Wkts']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train a Random Forest Regressor model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)





df_new = pd.DataFrame({
    'Ave': [20.0, 21.5, 19.8],  
    'Econ': [4.9, 5.1, 4.7]  
})


predicted_wickets = model.predict(df_new)


predicted_highest_wicket_taker = df.loc[df.index[np.argmax(predicted_wickets)], 'Player']

print(f'Predicted Highest Wicket-Taker for Upcoming Match against Australia: {predicted_highest_wicket_taker}')

Predicted Highest Wicket-Taker for Upcoming Match against Australia: Mohammed Shami